CREATE TABLE codenames_words (
    word_id SERIAL PRIMARY KEY,
    word_text VARCHAR(50) NOT NULL
);

INSERT INTO codenames_words (word_text) VALUES
    ('Kawałek'),
    ('Smok'),
    ('Ryba'),
    ('Księżyc'),
    ('Deszcz'),
    ('Wulkan'),
    ('Motyl'),
    ('Słońce'),
    ('Marzanna'),
    ('Telefon'),
    ('Książka'),
    ('Szachy'),
    ('Pizza'),
    ('Kangur'),
    ('Kometa'),
    ('Motocykl'),
    ('Lampa'),
    ('Banan'),
    ('Wiatr'),
    ('Orzeł'),
    ('Noga'),
    ('Drzewo'),
    ('Grafiti'),
    ('Grzyb'),
    ('Żółw'),
    ('Samolot'),
    ('Delfin'),
    ('Rakieta'),
    ('Narty'),
    ('Anioł'),
    ('Mikrofon'),
    ('Kwiat'),
    ('Zamek'),
    ('Klucz'),
    ('Serce'),
    ('Wulkan'),
    ('Pociąg'),
    ('Światło'),
    ('Kwiaty'),
    ('Deser'),
    ('Mleko'),
    ('Kameleon'),
    ('Świnka'),
    ('Magnet'),
    ('Smok'),
    ('Żaba'),
    ('Kula'),
    ('Komputer'),
    ('Wąż'),
    ('Rower');
